import { Product, Category, Condition, User } from './types';

export const CATEGORIES: Category[] = ['CPU', 'GPU', 'Motherboard', 'RAM', 'Storage', 'PSU', 'Case', 'Cooling', 'Other'];
export const CONDITIONS: Condition[] = ['New', 'Like New', 'Good', 'Used'];

export const DEMO_USERS: User[] = [
  { id: 1, name: 'KavinduP', isVerified: true },
  { id: 2, name: 'NimalS', isVerified: false },
  { id: 3, name: 'AyeshaF', isVerified: true },
  { id: 4, name: 'DhanushkaJ', isVerified: false },
  { id: 5, name: 'RaviG', isVerified: true },
  { id: 6, name: 'SamanL', isVerified: false },
];


export const DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'NVIDIA GeForce RTX 3080 Founders Edition',
    category: 'GPU',
    price: 150000,
    description: 'Well-maintained RTX 3080, used for light gaming for about a year. Never mined on. Comes with original box and accessories. Perfect for 1440p high refresh rate gaming.',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/rtx3080/800/600',
    seller: DEMO_USERS[0],
    datePosted: '2024-07-20',
    status: 'Available',
  },
  {
    id: 2,
    name: 'AMD Ryzen 7 5800X',
    category: 'CPU',
    price: 65000,
    description: 'Powerful 8-core, 16-thread CPU. Selling because I upgraded to the 5800X3D. Works perfectly, no bent pins. Thermal paste has been cleaned off.',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/ryzen5800x/800/600',
    seller: DEMO_USERS[1],
    datePosted: '2024-07-18',
    status: 'Available',
  },
  {
    id: 3,
    name: 'Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz',
    category: 'RAM',
    price: 18000,
    description: 'A reliable set of DDR4 RAM. Black heatspreaders. Ran stable with XMP profile enabled. Great for any modern build.',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/corsairram/800/600',
    seller: DEMO_USERS[2],
    datePosted: '2024-07-21',
    status: 'Available',
  },
  {
    id: 4,
    name: 'Samsung 970 Evo Plus 1TB NVMe M.2 SSD',
    category: 'Storage',
    price: 25000,
    description: 'Fast and reliable NVMe SSD. Used as a primary OS drive. CrystalDiskInfo report available on request, health is excellent. Selling due to an upgrade to a larger drive.',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/samsungssd/800/600',
    seller: DEMO_USERS[3],
    datePosted: '2024-07-19',
    status: 'Available',
  },
  {
    id: 5,
    name: 'ASUS ROG Strix B550-F Gaming Motherboard',
    category: 'Motherboard',
    price: 45000,
    description: 'Feature-rich B550 motherboard for AMD Ryzen CPUs. Has PCIe 4.0 support, great VRMs, and Aura Sync RGB. Comes with I/O shield, SATA cables, and original box.',
    condition: 'Like New',
    imageUrl: 'https://picsum.photos/seed/b550mobo/800/600',
    seller: DEMO_USERS[4],
    datePosted: '2024-07-22',
    status: 'Available',
  },
  {
    id: 6,
    name: 'Cooler Master Hyper 212 EVO CPU Cooler',
    category: 'Cooling',
    price: 7500,
    description: 'A classic budget air cooler that punches above its weight. Kept my CPU cool under load. Comes with all mounting hardware for Intel and AMD sockets.',
    condition: 'Used',
    imageUrl: 'https://picsum.photos/seed/hyper212/800/600',
    seller: DEMO_USERS[5],
    datePosted: '2024-07-15',
    status: 'Available',
  },
  {
    id: 7,
    name: 'Corsair RM750x 750W 80+ Gold PSU',
    category: 'PSU',
    price: 30000,
    description: 'Fully modular power supply. Very quiet and efficient. All original cables included in the pouch. Powered my rig without any issues.',
    condition: 'Good',
    imageUrl: 'https://picsum.photos/seed/corsairpsu/800/600',
    seller: DEMO_USERS[0],
    datePosted: '2024-07-21',
    status: 'Sold',
  },
  {
    id: 8,
    name: 'NZXT H510 Mid-Tower Case (White)',
    category: 'Case',
    price: 15000,
    description: 'Sleek and minimalist PC case. Tempered glass side panel has no scratches. A few minor scuffs on the back panel but not visible from the front. Includes two stock fans.',
    condition: 'Used',
    imageUrl: 'https://picsum.photos/seed/nzxtcase/800/600',
    seller: DEMO_USERS[1],
    datePosted: '2024-07-17',
    status: 'Available',
  }
];